// Auto-generated by scripts/gen-content-data.ts — DO NOT EDIT
// Source: src/content/products/*.mdoc

export interface ProductsEntry {
  slug: string;
  data: Record<string, unknown>;
  body: string;
}

export const products: ProductsEntry[] = [
  {
    "slug": "pc321-ty-smart-meter",
    "data": {
      "name": "PC321-W-TY Single/Three-Phase WiFi Smart Energy Clamp",
      "model": "PC321-W-TY",
      "slug": {
        "name": "PC321-W-TY Smart Energy Clamp",
        "slug": "pc321-w-ty"
      },
      "description": "Tuya-compatible WiFi smart energy clamp for single-phase, split-phase and three-phase systems. Three CT clamps up to 750A, bidirectional measurement for solar PV, real-time monitoring via Tuya Smart / Smart Life apps.",
      "productType": "smart-meters",
      "productSubType": "three-phase",
      "techSolution": "tuya",
      "techSubType": "tuya-meters",
      "communication": [
        "wifi"
      ],
      "ecosystem": [
        "tuya"
      ],
      "image": "https://documents.owon-iot.com/product-images/pc321-w-ty/pc321-w-ty-01.jpg?v=2",
      "images": [
        "https://documents.owon-iot.com/product-images/pc321-w-ty/pc321-w-ty-01.jpg?v=2",
        "https://documents.owon-iot.com/product-images/pc321-w-ty/pc321-w-ty-02.jpg",
        "https://documents.owon-iot.com/product-images/pc321-w-ty/pc321-w-ty-03.jpg",
        "https://documents.owon-iot.com/product-images/pc321-w-ty/pc321-w-ty-04.jpg",
        "https://documents.owon-iot.com/product-images/pc321-w-ty/pc321-w-ty-05.jpg"
      ],
      "specs": {
        "accuracy": "±1% (Voltmeters); Ammeters: ±1% (1-80A) / ±2% (0-1A) depending on CT rating",
        "voltage": "90~277 Vac 50/60Hz (RMS per phase)",
        "current": "80A~750A (CT dependent)",
        "frequency": "50/60Hz",
        "powerSupply": "<2W",
        "protocol": "WiFi 802.11 b/g/n @ 2.4GHz + BLE (pairing)",
        "dimensions": "86(W) x 37(D) x 86(H) mm",
        "mountingType": "Wall mounting (default); DIN rail mounting (optional)",
        "operatingTemp": "-20℃ to +55℃ (≤90% non-condensing)",
        "measuredParams": "Voltage, Current, Power Factor, Frequency, Active Power",
        "reportingCycle": "Every 15 seconds",
        "certification": "CE",
        "placeOfOrigin": "China",
        "brandName": "OWON",
        "supportedSystems": "Single-Phase, Split-Phase, Three-Phase 4-Wire (3-Phase 3-Wire & Delta not supported)",
        "clampInnerDimension": "80A (default): Ø10mm; 120A: Ø16mm; 200A: Ø20mm; 300A: Ø24mm; 500A: Ø36mm; 750A: Ø51mm",
        "ammeterAccuracy": "80A CT: ±1% (1-80A), ±2% (0-1A); 120A CT: ±1% (2-120A), ±2% (0-2A); 200A CT: ±1% (2-200A), ±2% (0-2A); 300A CT: ±1% (6-300A), ±2% (2-6A), ±5% (0-2A); 500A CT: ±1% (6-500A), ±2% (2-6A), ±5% (0-2A); 750A CT: ±1% (6-750A), ±2% (2-6A), ±5% (0-2A)",
        "wifi": "802.11 b/g/n @ 2.4GHz",
        "ble": "For Pairing"
      },
      "faqs": [
        {
          "q": "Does the Smart Power Meter (PC321) support both single-phase and three-phase systems?",
          "a": "Yes, it supports Single Phase / Split Phase / Three Phase power monitoring, making it flexible for residential and commercial projects."
        },
        {
          "q": "What CT clamp ranges are available?",
          "a": "The PC321 works with CT clamps from 80A up to 750A, suitable for HVAC, solar, and EV energy management applications."
        },
        {
          "q": "Is this WiFi energy meter Tuya-compatible?",
          "a": "Yes, it fully integrates with the Tuya IoT platform for remote monitoring and control."
        },
        {
          "q": "Can the PC321 integrate with BMS/EMS through MQTT?",
          "a": "Yes. The MQTT version supports custom integration with third-party IoT platforms."
        },
        {
          "q": "Does the PC321 support bidirectional metering?",
          "a": "Yes. It measures both energy import and export, ideal for solar PV systems."
        }
      ],
      "language": "en"
    },
    "body": "PC321-W-TY helps you monitor the amount of electricity Consumed and Produced in your three-phase power system by connecting the clamps on to the power cables. It is also compatible with single phase and split phase.\n\n## Key Features\n\n- Tuya compliant. Support automation with other Tuya device by export and import of grid or other energy values\n- Single Phase, Split Phase, 3-Phase 4-Wire electricity system compatible\n- Remotely monitor whole home Energy with three current transformers\n- Wireless communication via Wi-Fi 2.4GHz\n- Real-time Voltage, Current, PowerFactor, ActivePower, Frequency measurement\n- Bidirectional measurement: Energy Usage / Solar Production\n- Historical data can be displayed and exported in the App\n- External antenna prevents signal from being shielded\n\n## Packaging & Delivery\n\n- Selling Units: Single item"
  },
  {
    "slug": "pc321-w-3w",
    "data": {
      "name": "PC321-W/3W Single/Three-Phase WiFi MQTT Smart Energy Clamp",
      "model": "PC321-W/3W",
      "slug": {
        "name": "PC321-W/3W Smart Energy Clamp",
        "slug": "pc321-w-3w"
      },
      "description": "Open-protocol WiFi smart energy clamp for single, split and three-phase systems (incl. 3P3W). MQTT API with direct-to-cloud reporting — no third-party cloud required. Three CT clamps up to 750A, bidirectional measurement for solar PV.",
      "productType": "smart-meters",
      "productSubType": "three-phase",
      "techSolution": "mqtt",
      "techSubType": "mqtt-meters",
      "communication": [
        "wifi",
        "mqtt"
      ],
      "ecosystem": [
        "mqtt-open"
      ],
      "image": "https://documents.owon-iot.com/product-images/pc321-w-3w/pc321-w-3w-01.jpg",
      "images": [
        "https://documents.owon-iot.com/product-images/pc321-w-3w/pc321-w-3w-01.jpg",
        "https://documents.owon-iot.com/product-images/pc321-w-3w/pc321-w-3w-02.jpg"
      ],
      "specs": {
        "accuracy": "±1% (Voltmeters); Ammeters: ±1% (1-80A) / ±2% (0-1A) depending on CT rating",
        "voltage": "L-N: 90~277 Vac 50/60Hz; L-L: 156~480 Vac 50/60Hz",
        "current": "80A~750A (CT dependent)",
        "frequency": "50/60Hz",
        "powerSupply": "<2W",
        "protocol": "WiFi 802.11 b/g/n @ 2.4GHz + BLE (pairing); MQTT API",
        "mqtt": "Direct-to-cloud MQTT API — no third-party public cloud required",
        "dimensions": "86(W) x 37(D) x 86(H) mm",
        "mountingType": "Wall mounting (default); DIN rail mounting (optional)",
        "operatingTemp": "-20℃ to +55℃ (≤90% non-condensing)",
        "measuredParams": "Voltage, Current, Power Factor, Frequency, Active Power",
        "reportingCycle": "10s (default, configurable in integration)",
        "certification": "CE",
        "placeOfOrigin": "China",
        "brandName": "OWON",
        "supportedSystems": "Single-Phase, Split-Phase, Three-Phase (included 3-Phase 3-Wire)",
        "clampInnerDimension": "80A (default): Ø10mm; 120A: Ø16mm; 200A: Ø20mm; 300A: Ø24mm; 500A: Ø36mm; 750A: Ø51mm",
        "ammeterAccuracy": "80A CT: ±1% (1-80A), ±2% (0-1A); 120A CT: ±1% (2-120A), ±2% (0-2A); 200A CT: ±1% (2-200A), ±2% (0-2A); 300A CT: ±1% (6-300A), ±2% (2-6A), ±5% (0-2A); 500A CT: ±1% (6-500A), ±2% (2-6A), ±5% (0-2A); 750A CT: ±1% (6-750A), ±2% (2-6A), ±5% (0-2A)",
        "wifi": "802.11 b/g/n @ 2.4GHz",
        "ble": "For Pairing"
      },
      "faqs": [
        {
          "q": "How does the PC321-W/3W connect to my own cloud server?",
          "a": "It reports real-time data directly to your cloud server through the provided MQTT API — no third-party public cloud is required."
        },
        {
          "q": "Which electrical systems does the PC321-W/3W support?",
          "a": "Single-phase, split-phase and three-phase systems, including 3-phase 3-wire (3P3W) wiring."
        },
        {
          "q": "What CT clamp ranges are available?",
          "a": "CT clamps from 80A (default, Ø10mm opening) up to 750A (Ø51mm opening), covering HVAC, solar and EV energy management applications."
        },
        {
          "q": "Does it support bidirectional measurement?",
          "a": "Yes. It measures both energy usage and solar production — ideal for solar PV self-consumption monitoring."
        },
        {
          "q": "What is the reporting cycle?",
          "a": "10 seconds by default, and it can be configured during integration."
        }
      ],
      "language": "en"
    },
    "body": "PC321-W/3W helps you monitor the amount of electricity Consumed and Produced in your three-phase power system by connecting the clamps on to the power cables. It is also compatible with split-phase and single-phase. The real-time data can be reported directly to your cloud server without going through a third-party public cloud.\n\n## Key Features\n\n- Supports Wi-Fi 2.4GHz wireless communication, MQTT API provided.\n- External magnetic antenna can avoid shielding of wireless signals by metal distribution boxes\n- Three-Phase (included 3P3W), Split-Phase and Single-Phase electricity system compatible\n- Remotely monitor whole home Energy with three current transformers\n- Real-time Voltage, Current, PowerFactor, Frequency, ActivePower measurement\n- Bidirectional measurement: Energy Usage / Solar Production"
  },
  {
    "slug": "pc321-w",
    "data": {
      "name": "PC321-W Single/Three-Phase WiFi Smart Energy Clamp",
      "model": "PC321-W",
      "slug": {
        "name": "PC321-W Smart Energy Clamp",
        "slug": "pc321-w"
      },
      "description": "Tuya-compatible WiFi smart energy clamp with 2-second reporting and CT options from 80A to 1000A. Measures real-time voltage, current, power factor, active power and total energy for single and three-phase systems.",
      "productType": "smart-meters",
      "productSubType": "three-phase",
      "techSolution": "tuya",
      "techSubType": "tuya-meters",
      "communication": [
        "wifi"
      ],
      "ecosystem": [
        "tuya"
      ],
      "image": "https://documents.owon-iot.com/product-images/pc321-w/pc321-w-01.jpg",
      "images": [
        "https://documents.owon-iot.com/product-images/pc321-w/pc321-w-01.jpg",
        "https://documents.owon-iot.com/product-images/pc321-w/pc321-w-02.jpg"
      ],
      "specs": {
        "accuracy": "≤100W: ±2W; >100W: ±2%",
        "voltage": "100~240 Vac 50/60Hz",
        "current": "80A~1000A (CT dependent)",
        "frequency": "50/60Hz",
        "protocol": "WiFi 802.11 b/g/n (20/40MHz)",
        "wifi": "802.11 b/g/n (20/40MHz)",
        "rfRange": "Output Power: Up to +20dBm; external antenna",
        "dimensions": "86(L) x 86(W) x 37(H) mm",
        "operatingTemp": "-20℃ to +55℃ (≤90% non-condensing)",
        "measuredParams": "Voltage, Current, Power Factor, Active Power, Total Energy; device temperature display",
        "reportingCycle": "Every 2 seconds",
        "clampInnerDimension": "80A (default): Ø10.6mm; 120A: Ø16.7mm; 200A: Ø21.1mm; 300A: Ø25.1mm; 500A: Ø36.7mm; 750A: Ø51.3mm; 1000A: Ø51.3mm",
        "certification": "CE",
        "placeOfOrigin": "China",
        "brandName": "OWON"
      },
      "faqs": [
        {
          "q": "What is the PC321-W power clamp used for?",
          "a": "The PC321-W is a WiFi enabled energy monitoring device that measures electricity usage by attaching current transformer clamps to power cables, allowing installers and facility managers to track voltage, current, power, and total energy consumption in real time across electrical systems."
        },
        {
          "q": "Can the meter monitor single-phase and three-phase electrical systems?",
          "a": "Yes, the PC321-W supports single phase, split phase, and three phase electrical systems, making it suitable for residential homes, commercial buildings, and industrial facilities where different electrical configurations are used."
        },
        {
          "q": "What electrical parameters can the device measure?",
          "a": "The meter can measure voltage, current, active power, power factor, frequency, and total energy consumption, providing detailed energy data that helps users analyze load behavior and optimize energy efficiency."
        },
        {
          "q": "What current transformer options are available?",
          "a": "The device supports multiple CT clamp ranges including 80A, 120A, 200A, 300A, 500A, and up to 750A (1000A available), allowing it to be used for different loads such as HVAC equipment, EV chargers, industrial machines, and building power distribution systems."
        },
        {
          "q": "What types of projects typically deploy this power meter?",
          "a": "The PC321-W is commonly used in smart building energy monitoring, solar power systems, EV charging infrastructure, and facility energy management projects where real time electricity measurement and load analysis are required."
        }
      ],
      "language": "en"
    },
    "body": "PC321-W Power Clamp helps you monitor the amount of electricity usage in your facility by connecting the clamp on to the power cable. It can also measure Voltage, Current, PowerFactor, ActivePower.\n\n## Key Features\n\n- Single/3 - phase electricity compatible\n- Three current transformers for Single phase application\n- Measures real-time Voltage, Current, PowerFactor, ActivePower and total energy consumption\n- Display the current temperature of the device\n- Suitable for both residential and commercial application\n- Lightweight and easy to install\n- External antenna prevents signal from being shielded"
  },
  {
    "slug": "pc321-z-ty",
    "data": {
      "name": "PC321-Z-TY Single/Three-Phase ZigBee Smart Energy Clamp",
      "model": "PC321-Z-TY",
      "slug": {
        "name": "PC321-Z-TY Smart Energy Clamp",
        "slug": "pc321-z-ty"
      },
      "description": "Tuya-compatible ZigBee 3.0 smart energy clamp for single, split and three-phase systems. External antenna, OTA updates, real-time monitoring and automation via the Tuya platform.",
      "productType": "smart-meters",
      "productSubType": "three-phase",
      "techSolution": "tuya",
      "techSubType": "tuya-meters",
      "communication": [
        "zigbee"
      ],
      "ecosystem": [
        "tuya"
      ],
      "image": "https://documents.owon-iot.com/product-images/pc321-z-ty/pc321-z-ty-01.jpg",
      "images": [
        "https://documents.owon-iot.com/product-images/pc321-z-ty/pc321-z-ty-01.jpg",
        "https://documents.owon-iot.com/product-images/pc321-z-ty/pc321-z-ty-02.jpg",
        "https://documents.owon-iot.com/product-images/pc321-z-ty/pc321-z-ty-03.jpg",
        "https://documents.owon-iot.com/product-images/pc321-z-ty/pc321-z-ty-04.jpg",
        "https://documents.owon-iot.com/product-images/pc321-z-ty/pc321-z-ty-05.jpg"
      ],
      "specs": {
        "accuracy": "≤100W: ±2W; >100W: ±2%",
        "voltage": "100~240 Vac 50/60Hz",
        "current": "80A~750A (CT dependent)",
        "frequency": "50/60Hz",
        "protocol": "ZigBee 3.0 (2.4GHz IEEE 802.15.4)",
        "rfRange": "Output Power: Up to +20dBm; external antenna",
        "ota": "Support OTA",
        "dimensions": "86(L) x 86(W) x 37(H) mm",
        "operatingTemp": "-20℃ to +55℃ (≤90% non-condensing)",
        "measuredParams": "Voltage, Current, Active Power, Power Factor, Frequency, Total Energy",
        "reportingCycle": "Every 3 seconds",
        "clampInnerDimension": "80A (default): Ø10.6mm; 120A: Ø16.7mm; 200A: Ø21.1mm; 300A: Ø25.1mm; 500A: Ø36.7mm; 750A: Ø51.3mm",
        "certification": "CE",
        "placeOfOrigin": "China",
        "brandName": "OWON"
      },
      "faqs": [
        {
          "q": "What is the Zigbee Power Clamp PC321-Z-TY used for?",
          "a": "The PC321-Z-TY is a Zigbee enabled energy monitoring device designed to measure electricity consumption by attaching clamp on current transformers to power cables, allowing system integrators and facility managers to track voltage, current, power, and total energy usage in real time across electrical systems."
        },
        {
          "q": "Can this power clamp monitor both single-phase and three-phase systems?",
          "a": "Yes, the device supports single phase, split phase, and three phase electrical systems, making it suitable for a wide range of installations including residential energy monitoring, commercial buildings, and industrial facilities where multiple phases must be monitored simultaneously."
        },
        {
          "q": "How does the device integrate into smart energy management platforms?",
          "a": "Operating on the Zigbee 3.0 protocol, the meter can transmit real time power data to Zigbee gateways and IoT platforms, enabling integration with energy management systems, building management systems (BMS), and dashboards for centralized monitoring and automation."
        },
        {
          "q": "What electrical parameters can the meter measure?",
          "a": "The PC321-Z-TY can measure key electrical metrics including voltage, current, active power, power factor, frequency, and cumulative energy consumption, providing detailed data for energy analysis, load balancing, and efficiency optimization."
        },
        {
          "q": "What types of projects typically use this energy monitoring device?",
          "a": "This power clamp is commonly deployed in projects such as smart buildings, energy management systems, solar energy monitoring, EV charging infrastructure, and facility power monitoring where accurate measurement of electrical consumption is required for operational insights."
        },
        {
          "q": "How is the device installed in real project environments?",
          "a": "Installers typically mount the unit in an electrical panel and attach the clamp on current transformers around the monitored conductors, allowing non intrusive measurement of power usage without cutting or modifying existing wiring, which simplifies deployment in both retrofit and new installations."
        },
        {
          "q": "Does the meter support renewable energy monitoring such as solar systems?",
          "a": "Yes, the device supports bidirectional energy measurement, allowing it to monitor both electricity consumption and power generation from systems such as solar installations, which makes it suitable for smart energy and distributed energy management projects."
        }
      ],
      "language": "en"
    },
    "body": "PC321-Z-TY Power Clamp helps you monitor the amount of electricity usage in your facility by connecting the clamp on to the power cable. It can also measure Voltage, Current, ActivePower, total energy consumption.\n\n## Key Features\n\n- Tuya compliant\n- Support automation with other Tuya device\n- Single/3 - phase electricity compatible\n- Three current transformers for Single phase application\n- Measures real-time Voltage, Current, ActivePower and total energy consumption\n- Suitable for both residential and commercial application\n- Lightweight and easy to install\n- External antenna prevents signal from being shielded\n- Support OTA"
  },
  {
    "slug": "pc321",
    "data": {
      "name": "PC321 Single/Three-Phase ZigBee Smart Energy Clamp",
      "model": "PC321",
      "slug": {
        "name": "PC321 Smart Energy Clamp",
        "slug": "pc321"
      },
      "description": "ZigBee 3.0 smart energy clamp for single and three-phase systems. Works with SEG-X1/X3 gateways — up to 20 clamps per coordinator. Measures voltage, current, power and energy with 3-year server data storage.",
      "productType": "smart-meters",
      "productSubType": "three-phase",
      "techSolution": "zigbee",
      "techSubType": "zigbee-meters",
      "communication": [
        "zigbee"
      ],
      "ecosystem": [
        "zigbee-solution"
      ],
      "image": "https://documents.owon-iot.com/product-images/pc321/pc321-01.jpg",
      "images": [
        "https://documents.owon-iot.com/product-images/pc321/pc321-01.jpg",
        "https://documents.owon-iot.com/product-images/pc321/pc321-02.jpg",
        "https://documents.owon-iot.com/product-images/pc321/pc321-03.jpg",
        "https://documents.owon-iot.com/product-images/pc321/pc321-04.jpg",
        "https://documents.owon-iot.com/product-images/pc321/pc321-05.jpg"
      ],
      "specs": {
        "accuracy": "≤100W: ±2W; >100W: ±2%",
        "voltage": "100~240 Vac 50/60Hz",
        "current": "80A~300A (CT dependent)",
        "frequency": "50/60Hz",
        "powerSupply": "<1W",
        "protocol": "ZigBee 3.0 (2.4GHz IEEE 802.15.4)",
        "rfRange": "Outdoor/indoor: 100m / 30m; Output Power: Up to +19dBm",
        "antenna": "Internal antenna (default); external antenna (optional)",
        "gatewayCompatibility": "SEG-X1: up to 20 pcs; SEG-X3: up to 10 pcs",
        "dataStorage": "3 years on server",
        "dimensions": "86(L) x 86(W) x 37(H) mm",
        "weight": "415g",
        "operatingTemp": "-20℃ to +55℃ (≤90% non-condensing)",
        "measuredParams": "Irms, Vrms, Active Power & Energy, Reactive Power & Energy",
        "reportingCycle": "10s min (power change ≥1%) to 1min max (power change <1%); threshold settable in App",
        "clampInnerDimension": "80A (default): Ø10mm; 120A: Ø16mm; 200A: Ø20mm; 300A: Ø24mm",
        "certification": "CE",
        "placeOfOrigin": "China",
        "brandName": "OWON"
      },
      "faqs": [
        {
          "q": "What is the Three-Phase Energy Power Clamp PC321 and what does it monitor?",
          "a": "The PC321 is a three-phase power monitoring device that uses clamp-on current transformers to measure voltage, current, power, energy consumption, power factor, frequency, and other parameters across all three phases in real time, delivering essential insights for energy analysis, load balancing, and power quality management in industrial, commercial, and large residential installations."
        },
        {
          "q": "How does this device support smart energy management projects?",
          "a": "By transmitting comprehensive three-phase electrical data to networked dashboards, cloud platforms, or energy management systems (EMS), the PC321 enables energy service providers and building operators to analyze consumption patterns, optimize load distribution, reduce peak demand charges, and implement automated energy strategies that improve operational efficiency and lower utility costs."
        },
        {
          "q": "Can the PC321 integrate with building automation systems (BMS) and IoT platforms?",
          "a": "Yes, with appropriate network connectivity and APIs, the PC321 can share real-time and historical energy data with BMS, IoT platforms, and third-party dashboards, enabling centralized monitoring, threshold alerts, automated responses, and seamless integration into broader smart building or facility management solutions."
        },
        {
          "q": "What advantages does three-phase monitoring offer compared to single-phase meters?",
          "a": "Three-phase monitoring provides a complete picture of energy usage and balance across all power legs, helping identify phase imbalance issues, inefficiencies, and load spikes that single-phase meters cannot detect, making it especially valuable in commercial and industrial environments where power quality affects equipment performance and operational costs."
        },
        {
          "q": "Is this equipment suitable for large-scale energy efficiency and sustainability programs?",
          "a": "Absolutely — the PC321 supports scalable multi-point deployments across facilities, enabling enterprise-level energy tracking, reporting, benchmarking, and analytics, which are essential for sustainability initiatives, ISO 50001 energy management programs, and long-term cost reduction strategies."
        }
      ],
      "language": "en"
    },
    "body": "PC321 ZigBee Power Clamp helps you monitor the amount of electricity usage in your facility by connecting the clamp on to the power cable. It can also measure Voltage, Current, PowerFactor, ActivePower.\n\n## Key Features\n\n- ZigBee 3.0 compliant\n- Extend the range and strengthen ZigBee network communication\n- Single/3 - phase electricity compatible\n- Three current transformers for Single phase application\n- Measures real-time Voltage, Current, PowerFactor, ActivePower and total energy consumption\n- Statistical historical energy consumption\n- Suitable for both residential and commercial application\n- Optional antenna to enhance the signal strength\n- Lightweight and easy to install"
  },
  {
    "slug": "pc4713-w-e-ty-3w",
    "data": {
      "name": "PC4713-W-E-TY/3W Three Phase WiFi + Ethernet Smart Energy Meter",
      "model": "PC4713-W-E-TY/3W",
      "slug": {
        "name": "PC4713-W-E-TY/3W Smart Energy Meter",
        "slug": "pc4713-w-e-ty-3w"
      },
      "description": "Tuya-compatible three phase smart energy meter with WiFi 2.4GHz and Ethernet connectivity, 3 CT clamps up to 750A, bidirectional energy measurement for solar PV and home energy management.",
      "productType": "smart-meters",
      "productSubType": "three-phase",
      "techSolution": "tuya",
      "techSubType": "tuya-meters",
      "communication": [
        "wifi",
        "rj45"
      ],
      "ecosystem": [
        "tuya"
      ],
      "image": "https://documents.owon-iot.com/product-images/pc4713-w-e-ty-3w/pc4713-04.jpg",
      "images": [
        "https://documents.owon-iot.com/product-images/pc4713-w-e-ty-3w/pc4713-04.jpg",
        "https://documents.owon-iot.com/product-images/pc4713-w-e-ty-3w/pc4713-05.jpg",
        "https://documents.owon-iot.com/product-images/pc4713-w-e-ty-3w/pc4713-06.jpg",
        "https://documents.owon-iot.com/product-images/pc4713-w-e-ty-3w/pc4713-08.jpg",
        "https://documents.owon-iot.com/product-images/pc4713-w-e-ty-3w/pc4713-11.jpg"
      ],
      "specs": {
        "accuracy": "±1% (Voltmeters); Ammeters: ±1% (1-80A) / ±2% (0-1A) depending on CT rating",
        "voltage": "L-N: 90~277 Vac 50/60Hz; L-L: 156~480 Vac 50/60Hz",
        "current": "80A~750A (CT dependent)",
        "frequency": "50/60Hz",
        "powerSupply": "<2W",
        "protocol": "WiFi 802.11 b/g/n @ 2.4GHz + BLE (pairing) + Ethernet 10/100 Mbps",
        "dimensions": "19(W) x 69(D) x 90(H) mm",
        "mountingType": "35mm DIN rail mounting",
        "operatingTemp": "-20℃ to +55℃ (≤90% non-condensing)",
        "measuredParams": "Voltage, Current, Power Factor, Frequency, Active Power, Reactive Power, Apparent Power",
        "reportingCycle": "Every 15 seconds",
        "certification": "CE",
        "placeOfOrigin": "China",
        "brandName": "OWON",
        "supportedSystems": "Single-Phase, Split-Phase, Three-Phase (included 3-Phase 3-Wire)",
        "clampInnerDimension": "80A (default): Ø10mm; 120A: Ø16mm; 200A: Ø20mm; 300A: Ø24mm; 500A: Ø36mm; 750A: Ø51mm",
        "ammeterAccuracy": "80A CT: ±1% (1-80A), ±2% (0-1A); 120A CT: ±1% (2-120A), ±2% (0-2A); 200A CT: ±1% (2-200A), ±2% (0-2A); 300A CT: ±1% (6-300A), ±2% (2-6A), ±5% (0-2A); 500A CT: ±1% (6-500A), ±2% (2-6A), ±5% (0-2A); 750A CT: ±1% (6-750A), ±2% (2-6A), ±5% (0-2A)",
        "wifi": "802.11 b/g/n @ 2.4GHz",
        "ble": "For Pairing",
        "ethernet": "10/100 Mbps"
      },
      "faqs": [
        {
          "q": "What electrical systems does the PC4713 support?",
          "a": "The PC4713 supports single-phase, split-phase, three-phase four-wire, and three-phase three-wire electrical systems."
        },
        {
          "q": "Can the PC4713 monitor solar energy production?",
          "a": "Yes. The meter supports bidirectional energy measurement and can monitor both energy consumption and solar generation."
        },
        {
          "q": "Why does the PC4713 include Ethernet connectivity?",
          "a": "Ethernet provides a more reliable network connection than WiFi in many commercial and industrial environments, helping ensure stable communication and data reporting."
        },
        {
          "q": "How many CT clamps can be connected?",
          "a": "The PC4713 supports up to three CT clamps for monitoring multi-line electrical systems."
        },
        {
          "q": "Can I view historical energy data?",
          "a": "Yes. Historical energy records can be viewed through the Tuya platform by day, week, month, and year."
        },
        {
          "q": "How do I configure the network for the first time?",
          "a": "Download the Smart Life app, then either scan the QR code on the device or use Bluetooth pairing. For WiFi configuration you will need the 2.4GHz WiFi name and password; for Ethernet, plug in an internet-enabled Ethernet cable. If no device is detected, press and hold the Reset button for 5 seconds until the Net LED blinks slowly, then try again."
        }
      ],
      "language": "en"
    },
    "body": "PC4713-W-E-TY/3W helps you monitor the amount of electricity Consumed and Produced in your three-phase power system (included three phase three wire) by connecting the clamps on to the power cables. It is also compatible with split-phase and single-phase. It allows you to check real-time or historical energy data via mobile App.\n\n## Key Features\n- Tuya compliant. Support automation with other Tuya device by export and import of grid or other energy values\n- Three-Phase (included 3P3W), Split-Phase and Single-Phase electricity system compatible\n- Remotely monitor whole home Energy with three current transformers\n- Wireless communication via Wi-Fi 2.4GHz\n- Ethernet helps you improve the Network stability\n- Real-time Voltage, Current, PowerFactor, Frequency, ActivePower, ReactivePower, ApparentPower measurement\n- Bidirectional measurement: Energy Usage / Solar Production\n- Historical data could be displayed and exported in App\n\n## Packaging & Delivery\n- Selling Units: Single item"
  }
];
