// Auto-generated by scripts/gen-content-data.ts — DO NOT EDIT
// Source: src/content/solutions/*.mdoc

export interface SolutionsEntry {
  slug: string;
  data: Record<string, unknown>;
  body: string;
}

export const solutions: SolutionsEntry[] = [
  {
    "slug": "industrial-energy-submetering",
    "data": {
      "title": "Industrial Energy Submetering",
      "subtitle": "Granular per-machine energy tracking for factories and industrial facilities. MQTT integration with existing SCADA and BMS systems.",
      "industry": "industrial-iot",
      "productLines": [
        "smart-meters",
        "software-platforms"
      ],
      "techSolution": "mqtt",
      "caseStudies": [
        {
          "title": "Carbon Emission Monitoring with 4G Clamp-Type Smart Meter",
          "excerpt": "Commissioned by national energy agencies to develop a carbon emission monitoring system for commercial incentive and penalty purposes. Required a smart meter that installs without disrupting existing billing systems, supports single/split/three-phase circuits from 50A to 1000A, adapts to different cellular networks, and complies with local data privacy regulations.",
          "image": "https://documents.owon-iot.com/product-images/pc341-w-mqtt/pc341-w-mqtt-01.jpg",
          "caseSlug": "4g-clamp-meter-carbon"
        }
      ],
      "language": "en"
    },
    "body": "## The Challenge\n\nIndustrial facilities consume massive amounts of energy but lack per-machine visibility. A single production line may have 20+ machines, each with different energy profiles. Without granular data, energy waste goes undetected and unmanaged.\n\n## Our Solution\n\nOWON's Industrial Energy Submetering system provides per-machine energy monitoring with MQTT integration into existing industrial control systems.\n\n### Product Stack\n- **PC341-3M16S Multi-Circuit Monitors** — one unit monitors up to 16 machines\n- **PC321-TY Smart Meters** — for main feeder monitoring\n- **EdgeEco IoT Platform** — enterprise analytics and reporting\n\n### How It Works\n\n1. **Per-Machine Monitoring** — PC341 sub-CTs clamp onto individual machine circuits\n2. **MQTT Data Stream** — real-time energy data published to MQTT broker\n3. **SCADA Integration** — MQTT data consumed by existing industrial control systems\n4. **EdgeEco Analytics** — trend analysis, anomaly detection, cost allocation by machine\n\n## Architecture\n\n[Topology Diagram: Production Line Machines → PC341 CT clamps → MQTT Broker → SCADA/BMS + EdgeEco Cloud Analytics]"
  },
  {
    "slug": "senior-care-monitoring",
    "data": {
      "title": "Senior Care Monitoring System",
      "subtitle": "Non-intrusive health monitoring for elderly residents. Detect falls, track sleep quality, and alert caregivers in real time.",
      "industry": "senior-care",
      "productLines": [
        "senior-care",
        "software-platforms"
      ],
      "techSolution": "zigbee",
      "caseStudies": [
        {
          "title": "Five-Star Nursing Home — AiHome Wireless Monitoring System",
          "excerpt": "Dual-phase project: a new 16-story smart ward building (18,000 m², 380 beds) plus retrofitting of an older building (200 beds). Required resident monitoring, environmental sensing, energy management, and temperature control. Devices had to be wireless, battery-powered, and adhesive-mounted to avoid operational disruptions. Software needed to be modular with no custom coding, deployed on a local server for data privacy and offline resilience.",
          "image": "https://documents.owon-iot.com/product-images/fds315/fds315-01.jpg",
          "caseSlug": "senior-care-nursing-home"
        }
      ],
      "language": "en"
    },
    "body": "## The Challenge\n\nAging populations worldwide demand better senior care solutions. Traditional check-in rounds are labor-intensive and miss critical events between visits. Wearable devices are often refused by elderly residents due to discomfort and stigma.\n\n## Our Solution\n\nOWON's Senior Care Monitoring System uses non-contact sensors, emergency call buttons, and the AiJuan platform to provide continuous, dignified monitoring.\n\n### Product Stack\n- **SPM-915 Smart Sleep Monitors** — placed under mattresses, no wearables needed\n- **Emergency Call Buttons** — wall-mounted and portable options\n- **AiJuan Platform** — mobile app for caregivers + web dashboard for facility managers\n\n### How It Works\n\n1. **Continuous Monitoring** — SPM-915 pads track sleep quality, heart rate, and respiratory rate\n2. **Emergency Detection** — falls, prolonged inactivity, and abnormal vitals trigger alerts\n3. **Caregiver Notification** — AiJuan app sends push notifications with room number and event type\n4. **Analytics Dashboard** — facility managers see trends, compliance reports, and staffing recommendations"
  },
  {
    "slug": "smart-hotel-energy-management",
    "data": {
      "title": "Smart Hotel Energy Management",
      "subtitle": "Reduce energy costs with per-room monitoring and automated HVAC control across your entire property.",
      "industry": "smart-hotels",
      "productLines": [
        "smart-meters",
        "thermostats",
        "software-platforms"
      ],
      "techSolution": "zigbee",
      "caseStudies": [
        {
          "title": "Guest Room Management System for a Chain Resort Hotel",
          "excerpt": "The client sought a wireless IoT system to replace traditional wired BMS, which is expensive and difficult to install. They needed faster deployment, lower costs, and the ability to integrate both OWON and third-party smart devices through a unified gateway with device-level MQTT API. Some high-end locations also required Android-based touchscreen control panels.",
          "image": "https://documents.owon-iot.com/product-images/hero/thermostat-family-hero.png",
          "caseSlug": "hotel-room-management"
        }
      ],
      "language": "en"
    },
    "body": "## The Challenge\n\nHotels face rising energy costs and guest expectations for comfort. Traditional HVAC systems run 24/7 regardless of occupancy, wasting energy. Manual thermostat adjustments by staff are slow and inconsistent.\n\n## Our Solution\n\nOWON's Smart Hotel Energy Management system combines smart meters, room thermostats, and a centralized dashboard to deliver per-room energy visibility and automated control.\n\n### Product Stack\n- **PC341-3M16S Multi-Circuit Monitors** — per-floor or per-wing energy sub-metering\n- **PCT513 Touchscreen Thermostats** — in-room temperature control with occupancy detection\n- **EdgeEco IoT Platform** — centralized dashboard for facility managers\n\n### How It Works\n\n1. **Sub-metering** — PC341 monitors track energy consumption per floor, wing, or individual room\n2. **Smart Thermostats** — PCT513 units detect occupancy and adjust temperature automatically\n3. **Central Dashboard** — EdgeEco provides real-time analytics, alerts, and energy reports\n4. **Automated Rules** — set temperature setbacks during unoccupied hours\n\n## Architecture\n\n[Topology Diagram: PC341 monitors → ZigBee Gateway → EdgeEco Cloud → Facility Manager Dashboard. PCT513 thermostats communicate via ZigBee mesh to gateway.]"
  }
];
